### ISSUE TITLE
Publishing model doesn't follow casts

### ISSUE THREAD

**Issue by Froxz** [oddvalue/laravel-drafts#17]
I have a Model with a column that is casted to array

```php
protected $casts = [
        'my_col' => 'array',
 ];
```

After calling `publish()->save()` array is saved as wrapped in double quotes
![image](https://user-images.githubusercontent.com/3294939/220121282-4e785e50-3ce0-4ac4-880b-6c06f76efa97.png)

**Comment by oddvalue** [comment]
I've run some tests and haven't been able to replicate this issue. Could you share a minimal example app that shows the issue I could work from?

**Comment by Froxz** [comment]
> I've run some tests and haven't been able to replicate this issue. Could you share a minimal example app that shows the issue I could work from?

Hi @oddvalue I will test it later today, something tells me that I have this issue becuase of the column name`attributes`

**Comment by Froxz** [comment]
hi @oddvalue 

Nope is 

> > I've run some tests and haven't been able to replicate this issue. Could you share a minimal example app that shows the issue I could work from?
> 
> Hi @oddvalue I will test it later today, something tells me that I have this issue becuase of the column name`attributes`

Hi @oddvalue  Nope is not the case.

Basically I have a model `Page`

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use Oddvalue\LaravelDrafts\Concerns\HasDrafts;

class Page extends Model
{
    use HasDrafts, SoftDeletes;

    protected $table = 'pages';

    protected $attributes = [
        'name' => null,
        'traits' => "[]"
    ];
    protected $fillable = [
        'name',
        'traits'
    ];

    protected $casts = [
        'traits' => 'array'
    ];
}
```

Creating Draft via `$page->updateAsDraft($request->all())` works fine

But as soon as I call `$draft->publish()->save()`
This
```json
[{"type":"Text","value":"H1 Text","key":"h1"}]
```
is saved as this (in both Rows)

```json
"[{\"type\":\"Text\",\"value\":\"H1 Text\",\"key\":\"h1\"}]"
```

**Comment by oddvalue** [comment]
@Froxz I'm afraid I'm still not able to replicate this.

Using the example model provided, this test passes: 

```php
it('can create revisions without breaking casted attributes', function () {
    $post = Page::createDraft(['name' => 'foo', 'traits' => ['en' => 'Foo', 'de' => 'Baz']]);

    $post->traits = ['en' => 'Bar', 'de' => 'Qux'];
    $post->publish()->save();

    expect(Page::first()->traits)->toBe(['en' => 'Bar', 'de' => 'Qux']);
});
```

**Comment by Froxz** [comment]
Hi @oddvalue 

I'm digging through this now and it sound like laravel [issue](https://github.com/laravel/framework/issues/8972)

Also try chaning your test to this and you need to have `$casts = ['traits => 'array]`

```php
it('can create revisions without breaking casted attributes', function () {
    $post = Page::createDraft(['name' => 'foo', 'traits' => ['en' => 'Foo', 'de' => 'Baz']]);

    $post->publish()->save();

    expect(Page::first()->traits)->toBe(['en' => 'Bar', 'de' => 'Qux']);
});
```
See below (code from `setLive`:

```php
$published = $draft->revisions()->published()->first();

$oldAttributes = $published->getAttributes();
$newAttributes = $draft->getAttributes();

Arr::forget($oldAttributes, $draft->getKeyName());
Arr::forget($newAttributes, $draft->getKeyName());

$published->fill($newAttributes);
$draft->forceFill($oldAttributes);

dd($published);
```
![image](https://user-images.githubusercontent.com/3294939/220642188-f74a197d-58cd-4eb7-8ec8-d1746d4ac2a5.png)

As you can see `$published` after force fill is json_encoded one more time.

**Comment by Froxz** [comment]
So @oddvalue the solution here is to remove:

```php
protected $casts = [
    'traits' => 'object'
];
```

And add only getter

```php
protected function attributes(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => empty($value) ? json_decode("{}") : json_decode($value),
        );
    }
```
OR

```php
public function getAttributes()
    {
        $attributes = parent::getAttributes();

        foreach ($attributes as $name => $attribute) {
            if ($this->isJsonCastable($name)) {
                $attributes[$name] = $this->fromJson($attribute);
            }
        }

        return $attributes;
    }
```

**Comment by Froxz** [comment]
Hi @oddvalue unless is ok to change this (lines)(https://github.com/oddvalue/laravel-drafts/blob/main/src/Concerns/HasDrafts.php#L172)

to 

```php
$oldAttributes = $published?->getOriginal() ?? [];
$newAttributes = $this->getOriginal();
```

This actually solves my issue with casting

**Comment by oddvalue** [comment]
Hi @Froxz I'm afraid that would subtly alter the functionality of the package so I won't be able to make that change. Also, I replicated a test exactly as you specified and it passed so I'm still not sure as to why you're experiencing the issue and I'm not.

**Comment by Froxz** [comment]
Hi @oddvalue understand,

Maybe it is possible then to extract this 

```php
$oldAttributes = $published?->getAttributes() ?? [];
$newAttributes = $this->getAttributes();
```

To a function that can be overriden to have control over it? Becuase currently I've overriden the whole `setLive` function

Example:

```php
protected function getModelAttributes{
      return $this->getAttributes();
}

$oldAttributes = $published?->getModelAttributes() ?? [];
$newAttributes = $this->getModelAttributes();
```

**Comment by oddvalue** [comment]
Yeah, happy to do that if you want to submit a PR

**Comment by oddvalue** [comment]
Added to v1.3.0
