### ISSUE TITLE
No revisions: It does not show/get revisions

### ISSUE THREAD

**Issue by mansoorkhan96** [oddvalue/laravel-drafts#27]
I am able to create multiple revisions but they dont seem to get fetched with $model->revisions()->get()

<img width="837" alt="image" src="https://user-images.githubusercontent.com/51432274/235216141-82375897-f55b-41b5-89f0-74f973bcf13c.png">

**Comment by oddvalue** [comment]
I can't see any issue with this functionality. Could you provide a link to a repo that shows the issue in action?

**Comment by mansoorkhan96** [comment]
I was able to trace down the issue.

## Problem
These configs are preserved/stored in sessions. Once you define and it loads/saves to session, then you can not undo it unless you clear cookies/sessions.

Even if you set the reverse of the config, it would not help.

```php
# Enable preview mode
\Oddvalue\LaravelDrafts\Facades\LaravelDrafts::previewMode();
\Oddvalue\LaravelDrafts\Facades\LaravelDrafts::previewMode(true);

# Disable preview mode
\Oddvalue\LaravelDrafts\Facades\LaravelDrafts::disablePreviewMode();
\Oddvalue\LaravelDrafts\Facades\LaravelDrafts::previewMode(false);
```

## Possible Solution:
Maybe the configs should not be preserved to sessions. Allow the developer to set it inside the published config file.

**Comment by oddvalue** [comment]
I don't see how the preview mode feature is related to the issue of not being able to fetch the revisions. They're entirely unrelated. Also there is a test showing that disabling preview most does work https://github.com/oddvalue/laravel-drafts/blob/main/tests/PreviewModeTest.php#L11

Could you provide a link to a repo that shows the issue in action?

**Comment by oddvalue** [comment]
This issue has been closed because there has been no response to the request for more information from the original author. With only the information that is currently in the issue, there is not enough information to take action.
