### ISSUE TITLE
Intelephense error on Laravel 10

### ISSUE THREAD

**Issue by ibnu-ja** [oddvalue/laravel-drafts#32]
![image](https://github.com/oddvalue/laravel-drafts/assets/10094582/8e57e8ef-1b4a-48af-86b2-272393e0fcf2)

```php
    //  App\Http\Controllers\AlbumController
    /**
     * Show the form for editing the specified resource.
     */
    public function edit(int $album): \Inertia\Response
    {
        $album = Album::current()->findOrFail($album);

        return Inertia::render('Dashboard/Album/Edit', [
            'album' => $album,
        ]);
    }

```

Maybe docblock on [`HasDrafts.php line 18` ](https://github.com/oddvalue/laravel-drafts/blob/main/src/Concerns/HasDrafts.php#L18) is causing the issue. Any help?

**Environment:**
- Laravel Drafts 1.3.0
- Laravel 10.12.0
- PHP 8.2.3 nts
- PHP Intelephense 1.9.5
- VSCode 1.78.2
- Windows 11

**Comment by oddvalue** [comment]
Yep, that dockblock was completely wrong :sweat_smile: 
Fixed in v1.3.1

**Comment by ibnu-ja** [comment]
I still got
`Non static method 'current' should not be called statically.intelephense(1036)`

![image](https://github.com/oddvalue/laravel-drafts/assets/10094582/b37032af-a3ef-4b65-bd77-68d52fd2279d)

**Comment by oddvalue** [comment]
@ibnu-ja sorry, I forgot to put the `static` in the method doc. That in now, tagged v1.3.2
